import { Buttons } from "@retap/types";
import { FlexProps } from "@chakra-ui/react";

export let defaultNodeMenuStyles: FlexProps = {
  shadow: "xl",
  p: 2,
  position: "absolute",
  left: "50%",
  transform: "translateX(-50%)",
  top: 1,
  rounded: "md",
  gap: 1,
  zIndex: 2,
  alignItems: "center",
  bg: "white",
};

export let defaultToolbarStyles: FlexProps = {
  flexWrap: "wrap",
  alignItems: "center",
  gap: 1,
  p: 2,
  position: "sticky",
  top: 0,
  zIndex: 100,
  bg: "white",
};

export let defaultButtons: Buttons<{}> | undefined = [
  "leftAlign",
  "rightAlign",
  "centerAlign",
  "justifyText",
  "bulletList",
  "orderedList",
  "sinkList",
  "liftList",
  "clearLink",
  "undo",
  "redo",
  "bold",
  "italic",
  "underline",
  "strike",
  "list",
  "fontcolor",
  "highlightcolor",
  "subscript",
  "superscript",
  "linkInline",
  "link",
  "youtube",
  "image",
  "horizontalline",
  "hardbreak",
  "blockquote",
  "codeBlock",
  "heading",
  "fontfamily",
  "textalign",
  "clearformats",
  "clearcontents",
  "table",
  "deleteTable",
  "fontsize",
  "increaseIndent",
  "decreaseIndent",
  "video",
];
